### Pytorch's Automatic Differentiation Engine -- AUTOGRAD

##### Computaion Graph

##### Example 1

In [3]:
import torch

In [4]:
x=torch.tensor(3.0,requires_grad=True)
y=x**2


In [5]:
y

tensor(9., grad_fn=<PowBackward0>)

In [4]:
y.backward()

In [6]:
x.grad

In [7]:
x=torch.tensor(3.0, requires_grad=True)
y=x**2
z=torch.sin(y)

In [8]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [10]:
z.backward()

In [12]:
x.grad

tensor(-5.4668)

##### Example 2

In [99]:
x = torch.tensor([
    [1.0,2.0,3.0,4.0,5.0,6.0],
    [50.0,55.0,60.0,65.0,70.0,75.0],
])

y = torch.tensor([[0, 0, 0, 1, 1, 1]], dtype=torch.float32)




In [100]:
X_mean = x.mean(dim=1,keepdim=True)
X_range = x.max(dim=1,keepdim=True).values - x.min(dim=1,keepdim=True).values

X_norm = (x - X_mean) / X_range




In [101]:
print(X_norm)

tensor([[-0.5000, -0.3000, -0.1000,  0.1000,  0.3000,  0.5000],
        [-0.5000, -0.3000, -0.1000,  0.1000,  0.3000,  0.5000]])


In [102]:
torch.manual_seed(42)
w = torch.randn(2,1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)

In [103]:
print(w)
print(b)

tensor([[0.3367],
        [0.1288]], requires_grad=True)
tensor([0.], requires_grad=True)


In [104]:
z=torch.matmul(w.T,X_norm)+b
a=torch.sigmoid(z)

In [105]:
loss = -(y*torch.log(a+1e-8) + (1-y)*torch.log(1-a+1e-8)).mean()

In [106]:
print(loss)

tensor(0.6265, grad_fn=<NegBackward0>)


In [107]:
loss.backward()

In [108]:
print(w.grad)
print(b.grad)

tensor([[-0.1365],
        [-0.1365]])
tensor([0.])


In [109]:
print(a)

tensor([[0.4421, 0.4651, 0.4884, 0.5116, 0.5349, 0.5579]],
       grad_fn=<SigmoidBackward0>)
