In [1]:
import torch

In [2]:
X = torch.tensor([
    [1, 50],
    [2, 55],
    [3, 60],
    [4, 65],
    [5, 70],
    [6, 75]
], dtype=torch.float32)

In [3]:
Y = torch.tensor([[0], [0], [0], [1], [1], [1]],dtype=torch.float32)

In [4]:
X_mean = X.mean(dim=0,keepdim=True)
X_range = X.max(dim=0,keepdim=True).values - X.min(dim=0,keepdim=True).values

X2_norm = (X - X_mean) / X_range


In [5]:
X2_norm

tensor([[-0.5000, -0.5000],
        [-0.3000, -0.3000],
        [-0.1000, -0.1000],
        [ 0.1000,  0.1000],
        [ 0.3000,  0.3000],
        [ 0.5000,  0.5000]])

In [6]:
from torch.utils.data import Dataset, DataLoader


In [7]:
class CustomDataset(Dataset):

    def __init__(self,x,y):
        self.x=x
        self.y=y

    def __len__(self):
        return self.x.shape[0]
    
    def __getitem__(self,index):
        
        return self.x[index],self.y[index]


In [8]:
dataset= CustomDataset(X2_norm,Y)

In [10]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=False)

In [11]:
for batch_x,batch_y in dataloader:
    print(batch_x)
    print(batch_y)

tensor([[-0.5000, -0.5000],
        [-0.3000, -0.3000]])
tensor([[0.],
        [0.]])
tensor([[-0.1000, -0.1000],
        [ 0.1000,  0.1000]])
tensor([[0.],
        [1.]])
tensor([[0.3000, 0.3000],
        [0.5000, 0.5000]])
tensor([[1.],
        [1.]])
