In [3]:
import torch

In [4]:
print(torch.__version__)

2.5.1


In [5]:
### cuda for Windows(Accessing NVIDIA-GPU )
### mps for apple
### nothing for intel AMD( can run on cpu)

In [6]:
 torch.cuda.is_available()

False

In [7]:
print(torch.backends.mps.is_available())

True


In [8]:
device=torch.device("mps")

### undertanding the tensors

In [14]:
## 0-D , 1-D , 2-D Tensor , 3-D Tensor ( Checking the dimension)
tensor0d=torch.tensor(1.0)
tensor1d=torch.tensor([2,3,4,5],dtype=torch.float32)
tensor2d=torch.tensor([[2,3,4],[4,5,6]])
tensor3d=torch.tensor([[[1,2],[2,3]],[[4,5],[6,7]]],device=device)


In [21]:
print(tensor3d.dtype)

torch.int64


In [20]:
tensor3d.dim()
tensor3d.shape



torch.Size([2, 2, 2])

In [ ]:
tensor1d.dtype  ## by default 16-bit integer

torch.int64

In [45]:
tensor0d.dtype  ## by default 32-bit precision

torch.float32

In [22]:
float3d=tensor3d.to(torch.float32)  ## changing the precision
print(float3d.dtype)

torch.float32


In [23]:
float3d

tensor([[[1., 2.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]], device='mps:0')

### Common Pytorch tensor Operations

##### creating a Tensor

In [24]:
a=torch.empty(2,4) # using empty method

In [25]:
b=torch.zeros(2,3)  # using zero method

In [26]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones(2,3)  ## using one

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
torch.manual_seed(42)
c=torch.rand(2,3)  ## using random method

In [30]:
c

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [20]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

##### common operations

In [31]:
X= torch.tensor([[2,3,4],[4,5,6]])

In [32]:
X.shape

torch.Size([2, 3])

In [33]:
X.view(3,2) ## Reshapaing the matrix

tensor([[2, 3],
        [4, 4],
        [5, 6]])

In [73]:
X.T ## transpose

tensor([[2, 4],
        [3, 5],
        [4, 6]])

In [74]:
tensor2d.matmul(tensor2d.T)

tensor([[29, 47],
        [47, 77]])

##### Mathematical Operations

##### 1. Scalar Operation

In [35]:
X=torch.rand(2,3)
X

Y=torch.rand(2,3)
print(Y)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


In [39]:
# addition
print(X)
print(Y)
print(X+Y)
# subtraction , # mul , # div , # int div -> //
# mod --> %
# power -> **


tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
tensor([[1.1260, 1.3614, 1.6819],
        [0.5626, 1.8200, 1.1675]])


##### 2. Element Wise Operation

In [ ]:
# add , sub, multiply , division , power , mod
# abs-> .abs , # negative -> .neg , #round , ceil, floor 

##### 3. Reduction Operations

In [27]:
a= torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
torch.sum(a) # Total sum

# sum along column
print(torch.sum(a, dim=0))
# sum along row
print(torch.sum(a,dim=1))

# mean , # mean along column , # mean along rows
# median 
# max and min
# product
# standard deviation
# variamce

#argmax
#argmin


tensor([2., 2., 2.])
tensor([3., 3.])


##### 4. matrix Operations

In [ ]:
# matmul ,  Transpose , Determinant , Inverse

##### 5. special Function

In [ ]:
# log , sqrt , sigmoid, softmax-> (a, dim=0),relu

##### 6 . Inplace Operations

In [31]:
a= torch.rand(2,3)
b= torch.rand(2,3)

print(a)
print(b)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])
tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])


In [32]:
a.add_(b)

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])

In [37]:
print(id(b))

4708807872


##### 7 Copying Tensor

In [ ]:
### 1 . Typecast b=a
#### 2. use Clone function b=a.clone()

#### NumPy and Tensor

In [36]:
import numpy as np

In [40]:
a=torch.tensor([1,2,3])
print(type(a))


<class 'torch.Tensor'>


In [39]:
b=a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [41]:
c=np.array([1,2,3])


In [43]:
d= torch.from_numpy(c)
print(type(d))

<class 'torch.Tensor'>
